/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as SignUpIndexImport } from './routes/sign-up/index'
import { Route as RoadmapsIndexImport } from './routes/roadmaps/index'
import { Route as LoginIndexImport } from './routes/login/index'
import { Route as CoursesIndexImport } from './routes/courses/index'
import { Route as RoadmapsRoadmapIdImport } from './routes/roadmaps/$roadmapId'
import { Route as CoursesCourseIdImport } from './routes/courses/$courseId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SignUpIndexRoute = SignUpIndexImport.update({
  id: '/sign-up/',
  path: '/sign-up/',
  getParentRoute: () => rootRoute,
} as any)

const RoadmapsIndexRoute = RoadmapsIndexImport.update({
  id: '/roadmaps/',
  path: '/roadmaps/',
  getParentRoute: () => rootRoute,
} as any)

const LoginIndexRoute = LoginIndexImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRoute,
} as any)

const CoursesIndexRoute = CoursesIndexImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRoute,
} as any)

const RoadmapsRoadmapIdRoute = RoadmapsRoadmapIdImport.update({
  id: '/roadmaps/$roadmapId',
  path: '/roadmaps/$roadmapId',
  getParentRoute: () => rootRoute,
} as any)

const CoursesCourseIdRoute = CoursesCourseIdImport.update({
  id: '/courses/$courseId',
  path: '/courses/$courseId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/courses/$courseId': {
      id: '/courses/$courseId'
      path: '/courses/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof CoursesCourseIdImport
      parentRoute: typeof rootRoute
    }
    '/roadmaps/$roadmapId': {
      id: '/roadmaps/$roadmapId'
      path: '/roadmaps/$roadmapId'
      fullPath: '/roadmaps/$roadmapId'
      preLoaderRoute: typeof RoadmapsRoadmapIdImport
      parentRoute: typeof rootRoute
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesIndexImport
      parentRoute: typeof rootRoute
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexImport
      parentRoute: typeof rootRoute
    }
    '/roadmaps/': {
      id: '/roadmaps/'
      path: '/roadmaps'
      fullPath: '/roadmaps'
      preLoaderRoute: typeof RoadmapsIndexImport
      parentRoute: typeof rootRoute
    }
    '/sign-up/': {
      id: '/sign-up/'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/roadmaps/$roadmapId': typeof RoadmapsRoadmapIdRoute
  '/courses': typeof CoursesIndexRoute
  '/login': typeof LoginIndexRoute
  '/roadmaps': typeof RoadmapsIndexRoute
  '/sign-up': typeof SignUpIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/roadmaps/$roadmapId': typeof RoadmapsRoadmapIdRoute
  '/courses': typeof CoursesIndexRoute
  '/login': typeof LoginIndexRoute
  '/roadmaps': typeof RoadmapsIndexRoute
  '/sign-up': typeof SignUpIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/roadmaps/$roadmapId': typeof RoadmapsRoadmapIdRoute
  '/courses/': typeof CoursesIndexRoute
  '/login/': typeof LoginIndexRoute
  '/roadmaps/': typeof RoadmapsIndexRoute
  '/sign-up/': typeof SignUpIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/courses/$courseId'
    | '/roadmaps/$roadmapId'
    | '/courses'
    | '/login'
    | '/roadmaps'
    | '/sign-up'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/courses/$courseId'
    | '/roadmaps/$roadmapId'
    | '/courses'
    | '/login'
    | '/roadmaps'
    | '/sign-up'
  id:
    | '__root__'
    | '/'
    | '/courses/$courseId'
    | '/roadmaps/$roadmapId'
    | '/courses/'
    | '/login/'
    | '/roadmaps/'
    | '/sign-up/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CoursesCourseIdRoute: typeof CoursesCourseIdRoute
  RoadmapsRoadmapIdRoute: typeof RoadmapsRoadmapIdRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  RoadmapsIndexRoute: typeof RoadmapsIndexRoute
  SignUpIndexRoute: typeof SignUpIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CoursesCourseIdRoute: CoursesCourseIdRoute,
  RoadmapsRoadmapIdRoute: RoadmapsRoadmapIdRoute,
  CoursesIndexRoute: CoursesIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  RoadmapsIndexRoute: RoadmapsIndexRoute,
  SignUpIndexRoute: SignUpIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/courses/$courseId",
        "/roadmaps/$roadmapId",
        "/courses/",
        "/login/",
        "/roadmaps/",
        "/sign-up/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/courses/$courseId": {
      "filePath": "courses/$courseId.tsx"
    },
    "/roadmaps/$roadmapId": {
      "filePath": "roadmaps/$roadmapId.tsx"
    },
    "/courses/": {
      "filePath": "courses/index.tsx"
    },
    "/login/": {
      "filePath": "login/index.tsx"
    },
    "/roadmaps/": {
      "filePath": "roadmaps/index.tsx"
    },
    "/sign-up/": {
      "filePath": "sign-up/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
